"""empty message

Revision ID: 6fd6ae1b7390
Revises: 
Create Date: 2024-12-03 12:33:29.872991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd6ae1b7390'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion',
    sa.Column('id_calificacion', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id_calificacion')
    )
    op.create_table('categoria_servicios',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=250), nullable=True),
    sa.Column('nombre_servicio', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('mensajeria',
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.Column('mensajes', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('usuario',
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('apellido', sa.String(length=250), nullable=True),
    sa.Column('telfono', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('correo', sa.String(length=250), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(length=250), nullable=True),
    sa.Column('foto', sa.String(length=250), nullable=True),
    sa.Column('Rol', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('cedula')
    )
    op.create_table('Usuario_has_categoria_servicios',
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cedula'], ['usuario.cedula'], ),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_servicios.id_categoria'], ),
    sa.PrimaryKeyConstraint('cedula', 'id_categoria'),
    info={'bind_key': None}
    )
    op.create_table('Usuario_x_calificacion',
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('id_calificacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cedula'], ['usuario.cedula'], ),
    sa.ForeignKeyConstraint(['id_calificacion'], ['calificacion.id_calificacion'], ),
    sa.PrimaryKeyConstraint('cedula', 'id_calificacion'),
    info={'bind_key': None}
    )
    op.create_table('portafolio',
    sa.Column('id_portafolio', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('imagenes', sa.String(length=250), nullable=True),
    sa.Column('usuario_cedula', sa.Integer(), nullable=True),
    sa.Column('Usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Usuario'], ['usuario.cedula'], ),
    sa.PrimaryKeyConstraint('id_portafolio')
    )
    op.create_table('reserva',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora', sa.String(length=250), nullable=True),
    sa.Column('usuario_cedula', sa.Integer(), nullable=True),
    sa.Column('Categoria_servicios', sa.Integer(), nullable=True),
    sa.Column('Usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Categoria_servicios'], ['categoria_servicios.id_categoria'], ),
    sa.ForeignKeyConstraint(['Usuario'], ['usuario.cedula'], ),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_table('Mensaje_x_porta',
    sa.Column('id_portafolio', sa.Integer(), nullable=False),
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_mensaje'], ['mensajeria.id_mensaje'], ),
    sa.ForeignKeyConstraint(['id_portafolio'], ['portafolio.id_portafolio'], ),
    sa.PrimaryKeyConstraint('id_portafolio', 'id_mensaje'),
    info={'bind_key': None}
    )
    op.create_table('estado_servicio',
    sa.Column('id_estado_servicio', sa.Integer(), nullable=False),
    sa.Column('estado_pago', sa.String(length=250), nullable=True),
    sa.Column('reporte', sa.String(length=250), nullable=True),
    sa.Column('reserva_id_reserva', sa.Integer(), nullable=True),
    sa.Column('Reserva', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Reserva'], ['reserva.id_reserva'], ),
    sa.PrimaryKeyConstraint('id_estado_servicio')
    )
    op.create_table('historial',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('reserva_id_reserva', sa.Integer(), nullable=True),
    sa.Column('Reserva', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Reserva'], ['reserva.id_reserva'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial')
    op.drop_table('estado_servicio')
    op.drop_table('Mensaje_x_porta')
    op.drop_table('reserva')
    op.drop_table('portafolio')
    op.drop_table('Usuario_x_calificacion')
    op.drop_table('Usuario_has_categoria_servicios')
    op.drop_table('usuario')
    op.drop_table('rol')
    op.drop_table('mensajeria')
    op.drop_table('categoria_servicios')
    op.drop_table('calificacion')
    # ### end Alembic commands ###
